/// <reference types="nativewind/types" />
declare module "*.png" {
    const value: ImageSourcePropType;
    export default value;
}

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.